# Generated by Django 3.0.7 on 2020-06-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=45)),
                ('length', models.IntegerField(max_length=15)),
                ('track_amount', models.IntegerField(max_length=15)),
                ('out_date', models.DateField()),
                ('album_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField()),
                ('price', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='company_maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=17)),
                ('author', models.CharField(max_length=15)),
                ('performer', models.CharField(max_length=15)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salon_app.Album')),
            ],
        ),
        migrations.CreateModel(
            name='SellArrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_date', models.DateField()),
                ('op_code', models.CharField(choices=[('S', 'Sell'), ('A', 'Arrival')], max_length=1)),
                ('amount', models.IntegerField(max_length=15)),
                ('supplier', models.CharField(max_length=15)),
                ('price', models.IntegerField(max_length=15)),
                ('CD_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salon_app.CD')),
            ],
        ),
        migrations.CreateModel(
            name='CdHasAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salon_app.Album')),
                ('CD_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salon_app.CD')),
            ],
        ),
        migrations.AddField(
            model_name='cd',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salon_app.company_maker'),
        ),
    ]
