# Generated by Django 3.0.7 on 2020-06-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cd',
            name='name',
            field=models.CharField(default='Best hits', max_length=15),
            preserve_default=False,
        ),
    ]
