# Generated by Django 3.0.7 on 2020-06-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon_app', '0002_cd_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='author',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='track',
            name='performer',
            field=models.CharField(max_length=25),
        ),
    ]
